USE master;  
GO  

CREATE DATABASE DVDLibrary;
GO

CREATE TABLE DVD(
	DVDId INT IDENTITY (1,1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	ReleaseDate VARCHAR(4) NOT NULL,
	Director VARCHAR(20) NOT NULL,
	Rating VARCHAR(4) NOT NULL,
	Notes VARCHAR(100) NOT NULL
)